name: Set git config github actions

on:
  workflow_call:
    
jobs:
  set-git-config:   
    steps:
    
    - name: Set Git Config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
