name: Versioning with Conventional Commits

on:
  workflow_call:
    secrets:
      ALLOW_COMMITS:
        required: true

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  versioning:
    #if: github.event.commits[0].author.name != 'Github Actions'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{secrets.ALLOW_COMMITS}}
          # persist-credentials: false

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Target Branch
        run: echo running on branch ${{github.ref_name}}

      - name: Source Name
        run: echo running on branch ${{github.head_ref}}

      - name: Install dependencies
        run: npm ci

      - name: Set Git Config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - name: "Versioning Project with Conventional Commits"
        run: |
          if [ "${{github.ref}}" = "refs/heads/main" ]; then
            npx lerna version --force-publish --force-git-tag --conventional-commits --conventional-graduate --create-release github  --yes
          else
            npx lerna version --force-publish --no-git-tag-version --no-changelog --conventional-commits --conventional-prerelease --preid alpha --yes
          fi

      # Este bloco de código deve ser adicionado após o passo "Versioning Project with Conventional Commits".
      # Ele verifica se a branch atual é a main e, se for, faz o checkout para a develop,
      # faz um merge da main para a develop com a opção --strategy-option=ours e, em seguida,
      # faz um push das alterações para a develop.
      - name: Equalize main with develop
        run: |
          if [ "${{github.ref}}" = "refs/heads/main" ]; then
            git checkout develop
            git merge main --strategy-option=ours
            git push origin develop
          fi
