name: Checking code quality

on:
  workflow_call:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn

      - name: Run lerna bootstrap
        run: yarn lerna bootstrap
        
      - name: Check build
        run: yarn build
        
      - name: Check Lint
        run: yarn lint

      - name: Check Types
        run: yarn tsc:check
        
      - name: Check Test
        run: yarn test
