name: Versioning

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/heads/main')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: PATCH
        if: "startsWith(github.ref, 'refs/heads/hotfix/')"
        run: echo "PATCH"

      - name: MINOR
        if: "startsWith(github.ref, 'refs/heads/release/')"
        run: echo "MINOR"
