name: Versioning with branch name
on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Target Branch
        run:  echo running on branch ${GITHUB_REF_NAME}
      
      - name: Source Name
        run:  echo running on branch ${GITHUB_HEAD_REF}

      - name: Install dependencies
        run: yarn
  
      - name: Run lerna bootstrap
        run: yarn lerna bootstrap

      - name: "Configurando o Git"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
      
      - name: "Versioning Project with branch name (PATH)"
        if: "startsWith(github.head_ref, 'bug/')"
        run: yarn lerna version prepatch --yes

      - name: "Versioning Project with branch name (MINOR)"
        if: "startsWith(github.head_ref, 'feature/')"
        run: yarn lerna version preminor --yes

      - name: "Versioning Project with branch name (MAJOR)"
        if: "startsWith(github.head_ref, 'release/')"
        run: yarn lerna version premajor --yes
