name: Versioning with Conventional Commits

on:
  workflow_call:
    secrets:
      ALLOW_COMMITS:
        required: true

# permissions: write-all

jobs:
  versioning:
    if: github.event.commits[0].author.name != 'Github Actions'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # persist-credentials: false
          # token: ${{secrets.ALLOW_COMMITS}}
      - name: Enable Corepack
        run: corepack enable

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Target Branch
        run: echo running on branch ${{github.ref_name}}

      - name: Source Name
        run: echo running on branch ${{github.head_ref}}

      - name: Install dependencies
        run: yarn

      - name: Set Git Config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - name: "Versioning Project with Conventional Commits"
        run: |
          if [ "${{github.ref}}" = "refs/heads/main" ]; then
            yarn lerna version --force-publish --force-git-tag --conventional-commits --conventional-graduate --create-release github  --yes
          else
            yarn lerna version --force-publish --force-git-tag --conventional-commits --conventional-prerelease --preid alpha --yes
          fi
