name: Versioning

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Teste
        if: "startsWith(github.head_ref, 'refs/heads/hotfix/')"
        run: echo ${{github.head_ref}}

      - name: PATCH
        if: "startsWith(github.head_ref, 'refs/heads/hotfix/')"
        run: echo "PATCH"

      - name: MINOR
        if: "startsWith(github.head_ref, 'refs/heads/release/')"
        run: echo "MINOR"
