name: Versioning

on:
  push:

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Teste
        run: echo ${{github.ref}}

      - name: Teste
        run: echo ${{github.event}}

      - name: PATCH
        if: "startsWith(github.ref, 'refs/heads/hotfix/')"
        run: echo "PATCH"

      - name: MINOR
        if: "startsWith(github.ref, 'refs/heads/release/')"
        run: echo "MINOR"
